#!/usr/bin/env python3
"""Convert Markdown digest to HTML with styling."""

import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #1a1a2e;
            background: #f8f9fa;
            padding: 2rem 1rem;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.08);
            padding: 2.5rem;
        }}
        h1 {{
            font-size: 1.8rem;
            margin-bottom: 0.5rem;
            color: #16213e;
        }}
        h2 {{
            font-size: 1.3rem;
            margin-top: 2rem;
            margin-bottom: 0.8rem;
            color: #0f3460;
            border-bottom: 2px solid #e8e8e8;
            padding-bottom: 0.3rem;
        }}
        h3 {{
            font-size: 1.1rem;
            margin-top: 1.2rem;
            margin-bottom: 0.5rem;
            color: #533483;
        }}
        .meta {{
            color: #666;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
        }}
        .meta p {{ margin: 0.2rem 0; }}
        .overview {{
            background: #f0f4ff;
            border-left: 4px solid #0f3460;
            padding: 1rem 1.2rem;
            margin: 1rem 0;
            border-radius: 0 8px 8px 0;
        }}
        .video-card {{
            border: 1px solid #e8e8e8;
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1.5rem 0;
        }}
        .video-card .video-meta {{
            font-size: 0.85rem;
            color: #666;
        }}
        .video-card .video-meta a {{
            color: #0f3460;
        }}
        .tag {{
            display: inline-block;
            background: #e8e8ff;
            color: #533483;
            padding: 0.15rem 0.5rem;
            border-radius: 12px;
            font-size: 0.8rem;
            margin: 0.1rem;
        }}
        ul {{
            margin: 0.5rem 0 0.5rem 1.5rem;
        }}
        li {{
            margin: 0.3rem 0;
        }}
        hr {{
            border: none;
            border-top: 1px solid #e8e8e8;
            margin: 1.5rem 0;
        }}
        a {{ color: #0f3460; }}
        .themes {{
            margin: 1rem 0;
        }}
        .footer {{
            text-align: center;
            color: #999;
            font-size: 0.8rem;
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #e8e8e8;
        }}
    </style>
</head>
<body>
    <div class="container">
        {content}
        <div class="footer">
            Generated by iMessage AI Video Digest
        </div>
    </div>
</body>
</html>"""


def markdown_to_html_content(md_text: str) -> str:
    """Convert markdown to HTML content."""
    try:
        import markdown
        return markdown.markdown(md_text, extensions=["extra", "smarty"])
    except ImportError:
        # Basic fallback conversion
        import re
        html = md_text
        # Headers
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        # Links
        html = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', html)
        # List items
        html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        # Paragraphs
        html = re.sub(r'\n\n', '</p><p>', html)
        html = f'<p>{html}</p>'
        # Horizontal rules
        html = html.replace('<p>---</p>', '<hr>')
        return html


def build_html(md_text: str, title: str = "Weekly AI Video Digest") -> str:
    """Build a styled HTML page from markdown text."""
    content = markdown_to_html_content(md_text)
    return HTML_TEMPLATE.format(title=title, content=content)
