#!/usr/bin/env python3
"""Update the archive HTML page with links to all past digests."""

import json
import os
import sys
from datetime import datetime

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

ARCHIVE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Video Digest — Archive</title>
    <style>
        :root {{
            --bg: #f8f9fa;
            --card-bg: #ffffff;
            --text: #1a1a2e;
            --text-muted: #666666;
            --heading: #16213e;
            --border: #e8e8e8;
            --link: #0f3460;
            --hover-bg: #f0f4ff;
            --shadow: rgba(0,0,0,0.08);
        }}
        @media (prefers-color-scheme: dark) {{
            :root {{
                --bg: #0d1117;
                --card-bg: #161b22;
                --text: #e6edf3;
                --text-muted: #8b949e;
                --heading: #e6edf3;
                --border: #30363d;
                --link: #58a6ff;
                --hover-bg: #1f2430;
                --shadow: rgba(0,0,0,0.3);
            }}
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: var(--bg);
            padding: 2rem 1rem;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: var(--card-bg);
            border-radius: 12px;
            box-shadow: 0 2px 10px var(--shadow);
            padding: 2.5rem;
        }}
        h1 {{ font-size: 1.8rem; margin-bottom: 1rem; color: var(--heading); }}
        .digest-entry {{
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 1rem 1.2rem;
            margin: 0.8rem 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .digest-entry:hover {{ background: var(--hover-bg); }}
        .digest-date {{ font-weight: 600; color: var(--link); }}
        .digest-stats {{ color: var(--text-muted); font-size: 0.9rem; }}
        a {{ color: var(--link); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .footer {{
            text-align: center;
            color: var(--text-muted);
            font-size: 0.8rem;
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AI Video Digest Archive</h1>
        <p><a href="latest.html">View Latest Digest</a></p>
        <hr style="margin: 1rem 0; border: none; border-top: 1px solid var(--border);">
        {entries}
        <div class="footer">
            Generated by Tip10 Technologies
        </div>
    </div>
</body>
</html>"""


def update_archive(docs_dir: str, digests_dir: str):
    """Scan past digests and rebuild the archive page."""
    entries_html = []

    # Scan weekly-digests directory for date folders
    if os.path.exists(digests_dir):
        date_folders = sorted(
            [d for d in os.listdir(digests_dir) if os.path.isdir(os.path.join(digests_dir, d))],
            reverse=True,
        )

        for folder in date_folders:
            metadata_path = os.path.join(digests_dir, folder, "metadata.json")
            video_count = "?"

            if os.path.exists(metadata_path):
                with open(metadata_path) as f:
                    meta = json.load(f)
                video_count = meta.get("video_count", "?")

            html_file = f"{folder}.html"
            entries_html.append(
                f'<div class="digest-entry">'
                f'<span class="digest-date"><a href="{html_file}">{folder}</a></span>'
                f'<span class="digest-stats">{video_count} videos</span>'
                f'</div>'
            )

    if not entries_html:
        entries_html.append('<p style="color: #666; margin: 1rem 0;">No digests yet.</p>')

    html = ARCHIVE_TEMPLATE.format(entries="\n        ".join(entries_html))

    os.makedirs(docs_dir, exist_ok=True)
    archive_path = os.path.join(docs_dir, "archive.html")
    with open(archive_path, "w") as f:
        f.write(html)

    print(f"Updated archive with {len(entries_html)} entries")
